export { FolioClient, collect } from "./client.js";
export {
  FolioError,
  FolioTimeoutError,
  FolioNetworkError,
  type FolioClientOptions,
  type FolioRequestOptions,
  type RetryOptions,
  type FolioResponse,
  type StoredPdf,
  type StoredUrl,
  type GenerateRequest,
  type GenerateOptions,
  type HtmlOrUrl,
  type PaperOptions,
  type PaperSize,
  type MarginOptions,
  type RenderOptions,
  type MergeRequest,
  type SplitRequest,
  type CompressRequest,
  type PdfARequest,
  type ViewportOptions,
  type ClipRegion,
  type ScreenshotRequest,
  type ScreenshotOptions,
  type StoredImage,
} from "./types.js";
